"""Initial migration: create all tables

Revision ID: f9e7c5a456d9
Revises: 
Create Date: 2025-11-22 14:41:27.169930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9e7c5a456d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_transaction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_categories_name'), 'benefit_categories', ['name'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_table('category_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['benefit_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_keywords_category_id'), 'category_keywords', ['category_id'], unique=False)
    op.create_table('employee_benefit_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('annual_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['benefit_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'category_id', 'year', 'month', name='uq_employee_category_period')
    )
    op.create_index(op.f('ix_employee_benefit_balances_category_id'), 'employee_benefit_balances', ['category_id'], unique=False)
    op.create_index(op.f('ix_employee_benefit_balances_employee_id'), 'employee_benefit_balances', ['employee_id'], unique=False)
    op.create_table('reimbursement_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'APPROVED', 'REJECTED', 'PENDING_REVIEW', name='requeststatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('submission_timestamp', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['benefit_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursement_requests_category_id'), 'reimbursement_requests', ['category_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_employee_id'), 'reimbursement_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_requests_status'), 'reimbursement_requests', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['reimbursement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_request_id'), 'invoices', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_request_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_reimbursement_requests_status'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_reimbursement_requests_employee_id'), table_name='reimbursement_requests')
    op.drop_index(op.f('ix_reimbursement_requests_category_id'), table_name='reimbursement_requests')
    op.drop_table('reimbursement_requests')
    op.drop_index(op.f('ix_employee_benefit_balances_employee_id'), table_name='employee_benefit_balances')
    op.drop_index(op.f('ix_employee_benefit_balances_category_id'), table_name='employee_benefit_balances')
    op.drop_table('employee_benefit_balances')
    op.drop_index(op.f('ix_category_keywords_category_id'), table_name='category_keywords')
    op.drop_table('category_keywords')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_benefit_categories_name'), table_name='benefit_categories')
    op.drop_table('benefit_categories')
    # ### end Alembic commands ###

